---

homebrew:
  packages:
    - ansible
    - awless
    - awscli
    - antibody
    - bat
    - fzf
    - git
    - httpie
    - jq
    - kubectl
    - maven
    - minikube
    - navi
    - node
    - nvm
    - prettyping
    - python
    - speedtest
    - terraform
    - the_silver_searcher
    - thefuck
    - tldr
    - tree
    - yarn
    - zsh
  casks:
    - AdoptOpenJDK/openjdk
    - homebrew/cask-fonts
    - wallix/awless
  applications:
    - adoptopenjdk8 
    - adoptopenjdk11
    - dashlane
    - docker
    - firefox
    - font-hack-nerd-font
    - google-chrome
    - iterm2
    - karabiner-elements
    - jetbrains-toolbox
    - slack
    - visual-studio-code
