---
# miscellaneous configuration

- name: link git dotfiles
  file:
    src: "{{ files_path }}/.gitignore_global"
    dest: "$HOME/.gitignore_global"
    state: link
    force: yes
    follow: false
