---

# show status bar in finder
- osx_defaults:
    domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: true
    state: present
    
# show path bar in finder
- osx_defaults:
    domain: com.apple.finder
    key: ShowPathBar
    type: bool
    value: true
    state: present

# do the same as the key is duplicated (spelling mistake)
- osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: true
    state: present

# stop spaces rearranging
- osx_defaults:
    domain: -g com.apple.mouse.dock 
    key: mru-spaces
    type: bool
    value: false
    state: present

# enable right click
- osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.mouse
    key: MouseButtonMode
    type: string
    value: TwoButton
    state: present

# increase mouse speed
- osx_defaults:
    key: com.apple.mouse.scaling
    type: string
    value: 4
    state: present

- name: make Library directory visible
  command: chflags nohidden ~/Library

