---

- name: link vimrc
  file:
    src: "{{ files_path }}/.vimrc"
    dest: "$HOME/.vimrc"
    state: link
    force: yes
    follow: false

# install/update vim plugins using custom script and Vim's native plugin management
- name: run vim plugin script
  script: "vim-plug-man.sh"
