---

- name: link vimrc
  file:
    src: ".vimrc"
    dest: "~/.vimrc"
    state: link

# install/update vim plugins using custom script and Vim's native plugin management
- name: run vim plugin script
  script: "vim-plug-man.sh"
