---
- name: set files path
  set_fact:
    files_path: "{{ role_path }}/files"

- name: link dotfiles
  file:
    src: "{{ files_path }}/{{ item }}"
    dest: "${HOME}/{{ item }}"
    state: link
    force: yes
    follow: false
  loop:
    - .zshrc 
    - .zsh_aliases

# antibody static loading: https://getantibody.github.io/usage/
- name: static loading from plugins.txt
  shell: "antibody bundle < {{ files_path }}/zsh_plugins.txt > ~/.zsh_plugins"
  args:
    creates: ~/.zsh_plugins 

- name: Get zsh path
  command: which zsh 
  register: zsh_path

- name: Switch to zsh
  user: 
    name={{ ansible_user_id }} 
    shell={{ zsh_path.stdout }}
  become: true
